language: python

sudo: required
dist: focal

addons:
  apt:
    packages:
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - gettext
    - swig
    - dos2unix

python:
  - "2.7"

git:
  depth: 10

before_install:
    - pip install --upgrade pip autopep8 future
    - pip3 install --upgrade pip autopep8 future

script:
- echo compiling enigma2 plugins
- python -m compileall .
- find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
- echo done!

after_success:
- ./build.sh
